# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
use_frameworks! :linkage => linkage.to_sym if linkage

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.start_with?("Firebase")
      def pod.build_type; Pod::BuildType.dynamic_framework; end
      pod.recursive_dependent_targets.each do |dep_pod|
        def dep_pod.build_type; Pod::BuildType.dynamic_framework; end
      end
    end
  end
end

use_modular_headers!

target 'athlea' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  pod 'RNFlashList', :path => '../node_modules/@shopify/flash-list'
  pod 'react-native-keyboard-controller', :path => '../node_modules/react-native-keyboard-controller'
  pod 'react-native-pull-ups', :path => '../node_modules/react-native-pull-ups'
  pod 'nanopb'
  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  use_react_native!(
    :path => config[:reactNativePath],
    # :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'athleaTests' do
    inherit! :complete
    # Pods for testing
  end
  # Correctly defined post_install block
  post_install do |installer|
  
    # Existing post install for React Native
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  
    # Fix glog namespace issue
    installer.pods_project.targets.each do |target|
      if target.name == 'glog'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end

